.\" A man page for the Songlib music programming system
.\" Contact lusth@cs.ua.edu to correct errors or omissions. 
.TH man 3 "1  January 2008" "0.99.0" "Songlib man page"
.SH NAME
songlib \- a C library for music programming
.SH SYNOPSIS
.B -lsong
.SH DESCRIPTION
.B songlib
is a music programming library written for the C programming
language. Songlib uses a piano metaphor with library calls
such as
.I play,
.I chord,
.I rest,
and so on.
Songlib has support for programming using musical modes, such
as
.I Ionian
and
.I Aeolian.
.SH FILES
.P 
.I /usr/lib/songlib/*
.br
.I /usr/share/samples/*
.SH BUGS
None known.
.SH AUTHOR
.nf
John C. Lusth (lusth@cs.ua.edu)
.fi
.SH INTERNET RESOURCES
Main website and documentation:  http://songlib.cs.ua.edu/
.br
.SH LICENSING
Songlib is freely distributed without any guarantees or warranties.
.SH HISTORY
1 January 2009 \- Sway 0.99.0: First release.
