#!/bin/bash
for s in "$@"
    do
    chmod 644 "$s"
    name=`basename "$s" .flac`
    dir=`dirname "$s"`
    echo converting "$s" to MP3
    flac -s -f -d -c "$s" | lame - - > "$dir"/"$name".mp3
    done
