BINS=rplay \
	rra2flac rra2ogg rra2mp3\
	flac2rra flac2ogg flac2mp3 \
    mp32rra mp32wav mp32flac mp32ogg \
	ogg2mp3 ogg2flac ogg2rra \
	wma2mp3 wma2ogg\
	record monitor getpack getpack3 mkpack rraprep\
	rratreble\
	soxmaster rramaster\
	soxdeesser\
	soxfilter soxreverb soxchorus soxecho soxflanger soxtelephone soxbass soxxs
	#samples\
	#fixnotes\

install	:
		cp $(BINS) /usr/local/bin/

local 	: 
		cp $(BINS) ../../bin/

