#!/bin/bash

for s in "$@"
    do
    chmod 644 "$s"
    name=`basename "$s" .mp3`
    dir=`dirname "$s"`
    echo converting "$s" to RRA
    lame --decode "$s" .wav
    wav2rra .wav "$dir"/"$name".rra 
    rm -f .wav
    done

