#!/bin/bash
for s in "$@"
    do
    chmod 644 "$s"
    name=`basename "$s" .ogg`
    dir=`dirname "$s"`
    echo converting "$s" to RRA
    sox "$s" "$dir"/"$name".wav
    wav2rra "$dir"/"$name".wav "$dir"/"$name".rra
    rm -f "$dir"/"$name.wav"
    done
